apiVersion: v1
kind: Service
metadata:
  name: crystal-ball-ui-service
  labels:
    app: crystal-ball-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: crystal-ball-ui
